import '../constants/game_constants.dart';
import '../../data/models/user_progress.dart';

/// Pure heart-regeneration math: given how much wall-clock time has
/// passed since the last heart was lost, how many hearts should have
/// regenerated by [now].
///
/// This is a **safety net, not a gate.** Hearts are a per-attempt life
/// budget that is restored in full whenever a lesson starts (see
/// `ProgressController.refillHeartsForSession`), so no learner ever waits
/// on this clock — the app shows no heart timer, offers no ad, no
/// refill and no paywall. Regeneration stays only so a partially-spent
/// budget heals for anyone who leaves mid-attempt and comes back.
///
/// Premium deliberately plays no part here: Pro unlocks content, not
/// hearts.
class HeartsLogic {
  HeartsLogic._();

  static UserProgress regenerate(UserProgress progress, DateTime now) {
    if (progress.hearts >= GameConstants.maxHearts ||
        progress.lastHeartLostAt == null) {
      return progress;
    }

    final elapsed = now.difference(progress.lastHeartLostAt!);
    final regenerated =
        elapsed.inMilliseconds ~/ GameConstants.heartRegenInterval.inMilliseconds;
    if (regenerated <= 0) return progress;

    final newHearts = (progress.hearts + regenerated).clamp(
      0,
      GameConstants.maxHearts,
    );

    if (newHearts >= GameConstants.maxHearts) {
      return progress.copyWith(
        hearts: GameConstants.maxHearts,
        clearLastHeartLostAt: true,
      );
    }

    // Carry forward the remainder so partial regen time isn't lost.
    final consumedMs = regenerated * GameConstants.heartRegenInterval.inMilliseconds;
    final newLastLost =
        progress.lastHeartLostAt!.add(Duration(milliseconds: consumedMs));

    return progress.copyWith(hearts: newHearts, lastHeartLostAt: newLastLost);
  }

  static DateTime? nextHeartAt(UserProgress progress) {
    if (progress.hearts >= GameConstants.maxHearts) return null;
    return progress.lastHeartLostAt?.add(GameConstants.heartRegenInterval);
  }
}
